# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - 'db/migrate/*'

Metrics/ClassLength:
  Enabled: true
  Max: 100

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
